create table if not exists public.runs (
  id bigint generated by default as identity primary key,
  name text not null,
  bike text not null,
  device_id text,
  race_date date not null,
  lap1 numeric not null check (lap1 > 0),
  lap2 numeric check (lap2 > 0),
  lap3 numeric check (lap3 > 0),
  created_at timestamptz not null default now()
);

alter table public.runs add column if not exists device_id text;
alter table public.runs alter column lap2 drop not null;
alter table public.runs alter column lap3 drop not null;

alter table public.runs enable row level security;

revoke select on public.runs from anon;
grant select (id, name, bike, race_date, lap1, lap2, lap3, created_at) on public.runs to anon;
grant insert (name, bike, device_id, race_date, lap1, lap2, lap3) on public.runs to anon;
grant delete on public.runs to anon;

drop policy if exists "Public can read runs" on public.runs;
create policy "Public can read runs"
on public.runs
for select
to anon
using (true);

drop policy if exists "Public can add runs" on public.runs;
create policy "Public can add runs"
on public.runs
for insert
to anon
with check (
  length(trim(name)) between 1 and 80
  and length(trim(bike)) between 1 and 80
  and race_date between date '2020-01-01' and current_date + interval '1 day'
  and lap1 > 0
  and (
    (lap2 is null and lap3 is null)
    or (lap2 > 0 and lap3 > 0)
  )
  and (device_id is null or length(trim(device_id)) between 20 and 120)
);

drop policy if exists "Public can delete own device runs" on public.runs;
create policy "Public can delete own device runs"
on public.runs
for delete
to anon
using (
  device_id is not null
  and device_id = coalesce(
    nullif(current_setting('request.headers', true), '')::jsonb ->> 'x-device-id',
    ''
  )
);
