create table if not exists public.runs (
  id bigint generated by default as identity primary key,
  name text not null,
  bike text not null,
  race_date date not null,
  lap1 numeric not null check (lap1 > 0),
  lap2 numeric not null check (lap2 > 0),
  lap3 numeric not null check (lap3 > 0),
  created_at timestamptz not null default now()
);

alter table public.runs enable row level security;

drop policy if exists "Public can read runs" on public.runs;
create policy "Public can read runs"
on public.runs
for select
to anon
using (true);

drop policy if exists "Public can add runs" on public.runs;
create policy "Public can add runs"
on public.runs
for insert
to anon
with check (
  length(trim(name)) between 1 and 80
  and length(trim(bike)) between 1 and 80
  and race_date between date '2020-01-01' and current_date + interval '1 day'
  and lap1 > 0
  and lap2 > 0
  and lap3 > 0
);
